pick_place_demo:
# /**:
  ros__parameters:
    arm_group_name: "arm"
    object_marker_id: 42
    place_marker_id: 43 #43
    detect_state_name: "detect"
    ik_frame: "tool_tip"
    pre_pick_offset: [0.002, -0.013, 0.15]
    pick_offset: [0.0, 0.0, 0.040] # pincer_height:0.014
    pre_place_offset: [0.006, -0.006, 0.15]
    place_offset: [0.0, 0.0, 0.07]
    retreat_offset: [0.0, 0.0, 0.3]
    box_size: [0.017, 0.017, 0.017]
    lift_distance: 0.15
    path_constraints_file: "path_constraints.yaml"
    io_gripper_with_ur_skill:
      io_service_name: "/io_and_status_controller/set_io"
      # io_service_name: "/mock_io_server/set_io"
      timeout: 5.0
    detect_aruco_marker_skill:
      marker_topic_name: "/marker_publisher/markers"
      find_marker_timeout_seconds: 7
    compute_path_moveitcpp_skill:
      planning_pipeline: "pilz_industrial_motion_planner"
      planner_id: "LIN"
      planning_attempts: 10
      step_size: 0.005
      min_fraction: 0.50
      max_acceleration_scaling_factor: 0.3
      max_velocity_scaling_factor: 0.1
      planning_time: 1.0
