waypoints:
  frame_id: world
  poses:
    - position:
        x: -0.17
        y: 0.16
        z: 1.25
    - position:
        x: -0.17
        y: 0.16
        z: 1.06
    - position:
        x: -0.17
        y: -0.10
        z: 1.25
    - position:
        x: -0.17
        y: -0.10
        z: 1.10
