waypoints:
  frame_id: world
  poses:
    - position:
        x: -0.17
        y: 0.163
        z: 1.25
    - position:
        x: -0.17
        y: 0.163
        z: 1.067
    - position:
        x: -0.17
        y: -0.103
        z: 1.25
    - position:
        x: -0.17
        y: -0.103
        z: 1.10
